# Basic Functions

In [2]:
import numpy as np
array1=np.array([[3,2,6,7,9],[1,12,3,4,5]],dtype='int32')
print(array1)

[[ 3  2  6  7  9]
 [ 1 12  3  4  5]]


In [3]:
array1.shape

(2, 5)

In [4]:
array1.dtype

dtype('int32')

In [5]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones(6).dtype

dtype('float64')

In [22]:
np.empty((4,6)).dtype

dtype('float64')

In [8]:
array1

array([[ 3,  2,  6,  7,  9],
       [ 1, 12,  3,  4,  5]])

In [9]:
array1*array1

array([[  9,   4,  36,  49,  81],
       [  1, 144,   9,  16,  25]])

In [10]:
array1+array1

array([[ 6,  4, 12, 14, 18],
       [ 2, 24,  6,  8, 10]])

In [11]:
array1-array1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
array1**array1

array([[        27,          4,      46656,     823543,  387420489],
       [         1, -251658240,         27,        256,       3125]])

In [13]:
12**12

8916100448256

In [14]:
1/array1

array([[0.33333333, 0.5       , 0.16666667, 0.14285714, 0.11111111],
       [1.        , 0.08333333, 0.33333333, 0.25      , 0.2       ]])

## Slicing

In [15]:
array2=np.array([5,4,64,3,3,3])

In [16]:
arr = array2[4:6]

In [17]:
arr

array([3, 3])

In [18]:
arr[0]=9

In [19]:
array2

array([ 5,  4, 64,  3,  9,  3])

In [20]:
array1

array([[ 3,  2,  6,  7,  9],
       [ 1, 12,  3,  4,  5]])

In [21]:
array1[0,3]

7